### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by andris155** [OpticFusion1/Slimefun-Reloaded#12]
<img width="841" alt="Annotation 2019-12-26 184111" src="https://user-images.githubusercontent.com/8324198/71484970-4e35f180-280f-11ea-8871-1f3f3e0a5164.png">

**Comment by OpticFusion1** [comment]
woops, wrong label, either way next commit will deal with this

**Comment by OpticFusion1** [comment]
I knew i had to remove something though, just forgot what it was ._.
